sonar.projectKey=haniellymarquesdeveloper-web_nexo-on
sonar.organization=haniellymarquesdeveloper-web
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.venv/**,**/__pycache__/**,**/dist/**,**/build/**,**/.git/**,**/.github/**,**/.vscode/**,**/.idea/**,**/.env/**,**/.docker/**,**/.dockerignore/**,**/.editorconfig/**,**/.eslintignore/**,**/.prettierignore/**,**/.gitignore/**,**/sonar-project.properties
sonar.host.url=https://sonarcloud.io